### ISSUE TITLE
Freshclam-ClamAV - Database Download - blocked by CDN

### ISSUE THREAD

**Issue by maglan2101** [Cisco-Talos/clamav#1066]
Hello,

I installed a new server with ClamAV version 1.0.3.
Freshclam gives following error message:

> 2023-10-23T09:30:31.937429+02:00 srv freshclam[9672]: WARNING: Mon Oct 23 09:30:31 2023 -> You are on cool-down until after: 2023-10-24 09:30:31
> 2023-10-23T09:30:31.937447+02:00 srv freshclam[9672]: ERROR: Mon Oct 23 09:30:31 2023 -> Database update process failed: Forbidden; Blocked by CDN
> 2023-10-23T09:30:31.937476+02:00 srv freshclam[9672]: ERROR: Mon Oct 23 09:30:31 2023 -> Update failed.
> 2023-10-23T09:30:31.937497+02:00 srv freshclam[9672]: WARNING: Mon Oct 23 09:30:31 2023 -> FreshClam was forbidden from downloading a database.
> 2023-10-23T09:30:31.937515+02:00 srv freshclam[9672]: WARNING: Mon Oct 23 09:30:31 2023 -> This is fatal. Retrying later won't help. Exiting now.
> 2023-10-23T09:30:31.939250+02:00 srv systemd[1]: clamav-freshclam.service: Main process exited, code=exited, status=17/n/a
> 2023-10-23T09:30:31.939351+02:00 srv systemd[1]: clamav-freshclam.service: Failed with result 'exit-code'.

My IP address: 128.140.100.105.

Could you whitelist me?

Thank you!

BR,
Manuel

**Comment by maglan2101** [comment]
Do you need more information?
I guess there is nothing I can do on my side.

Thank you.

**Comment by micahsnyder** [comment]
@maglan2101 Sorry about the delay.  It should be fixed now.  We had an issue with Cloudflare's bot detection logic stopping freshclam updates for some people.  In their defense, freshclam should look like a bot 😆  Anyways, we disabled it yesterday for our database server when we realized.   Our cloudflare account admin looked up your IP and found yours was affected and blocked as a result.  He says it should be fixed now.  Sorry about the trouble.

**Comment by maglan2101** [comment]
Hello,

thank you, but the problem still exists:

> 2023-10-27T19:45:43.853261+02:00 srv systemd[1]: Started clamav-freshclam.service - ClamAV virus database updater.
> 2023-10-27T19:45:43.861977+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 -> ClamAV update process started at Fri Oct 27 19:45:43 2023
> 2023-10-27T19:45:43.863199+02:00 srv freshclam[2825]: WARNING: Fri Oct 27 19:45:43 2023 -> Cool-down expired, ok to try again.
> 2023-10-27T19:45:43.863292+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 -> daily database available for download (remote version: 27074)
> 2023-10-27T19:45:43.927576+02:00 srv freshclam[2825]: WARNING: Fri Oct 27 19:45:43 2023 -> Can't download daily.cvd from https://database.clamav.net/daily.cvd
> 2023-10-27T19:45:43.927689+02:00 srv freshclam[2825]: WARNING: Fri Oct 27 19:45:43 2023 -> FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN).
> 2023-10-27T19:45:43.927720+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 -> This could mean several things:
> 2023-10-27T19:45:43.927750+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 ->  1. You are running an out-of-date version of ClamAV / FreshClam.
> 2023-10-27T19:45:43.927797+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 ->     Ensure you are the most updated version by visiting https://www.clamav.net/downloads
> 2023-10-27T19:45:43.927827+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 ->  2. Your network is explicitly denied by the FreshClam CDN.
> 2023-10-27T19:45:43.927851+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 ->     In order to rectify this please check that you are:
> 2023-10-27T19:45:43.927879+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 ->    a. Running an up-to-date version of FreshClam
> 2023-10-27T19:45:43.927908+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 ->    b. Running FreshClam no more than once an hour
> 2023-10-27T19:45:43.927932+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 ->    c. If you have checked (a) and (b), please open a ticket at
> 2023-10-27T19:45:43.927963+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 ->       https://github.com/Cisco-Talos/clamav/issues
> 2023-10-27T19:45:43.927992+02:00 srv freshclam[2825]: Fri Oct 27 19:45:43 2023 ->       and we will investigate why your network is blocked.
> 2023-10-27T19:45:43.928020+02:00 srv freshclam[2825]: WARNING: Fri Oct 27 19:45:43 2023 -> You are on cool-down until after: 2023-10-28 19:45:43
> 2023-10-27T19:45:43.928047+02:00 srv freshclam[2825]: ERROR: Fri Oct 27 19:45:43 2023 -> Database update process failed: Forbidden; Blocked by CDN
> 2023-10-27T19:45:43.928080+02:00 srv freshclam[2825]: ERROR: Fri Oct 27 19:45:43 2023 -> Update failed.
> 2023-10-27T19:45:43.928109+02:00 srv freshclam[2825]: WARNING: Fri Oct 27 19:45:43 2023 -> FreshClam was forbidden from downloading a database.
> 2023-10-27T19:45:43.928137+02:00 srv freshclam[2825]: WARNING: Fri Oct 27 19:45:43 2023 -> This is fatal. Retrying later won't help. Exiting now.

Could you check it again please?

Thank you in advance.

BR,
Manuel

**Comment by micahsnyder** [comment]
@maglan2101 I asked our CF admin to take a look.  I'm told we no longer have any logs for your 128.140.100.105 IP address for the past 72 hours. 
 
It's possible that Cloudflare is now/also blocking your 128.140.100.105 IP by an incorrect geo-IP lookup.  Either that or your public IP has changed since then so we're looking for the wrong IP in our logs.

**Comment by micahsnyder** [comment]
If you can gather the `cf-ray` ID from freshclam verbose log output we may be able to find the specific block event in the logs that way. 

To get that `cf-ray` ID, first remove the `freshclam.dat` file from your database directory (probably in `/var/lib/clamav/freshclam.dat` or `/usr/local/share/clamav/freshclam.dat`).  You'll have to delete this file so freshclam does not self-limit itself after observing that it is being limited or blocked.

Then try running freshclam with the `--verbose` option.

From the verbose log where you see the 403 HTTP response from the server, please grab the `cf-ray` ID.  It will look something like this
```
< server: cloudflare
< cf-ray: 81b3b1069af6f957-SJC
```

**Comment by maglan2101** [comment]
Hello,

thank you for your response.
My IP Adress is still the same.

The output of freshclam --verbose:

> Sat Oct 28 10:15:22 2023 -> Current working dir is /var/lib/clamav/
> Sat Oct 28 10:15:22 2023 -> Can't open freshclam.dat in /var/lib/clamav
> Sat Oct 28 10:15:22 2023 -> It probably doesn't exist yet. That's ok.
> Sat Oct 28 10:15:22 2023 -> Failed to load freshclam.dat; will create a new freshclam.dat
> Sat Oct 28 10:15:22 2023 -> Creating new freshclam.dat
> Sat Oct 28 10:15:22 2023 -> Saved freshclam.dat
> Sat Oct 28 10:15:22 2023 -> ClamAV update process started at Sat Oct 28 10:15:22 2023
> Sat Oct 28 10:15:22 2023 -> Current working dir is /var/lib/clamav/
> Sat Oct 28 10:15:22 2023 -> Querying current.cvd.clamav.net
> Sat Oct 28 10:15:22 2023 -> TTL: 1622
> Sat Oct 28 10:15:22 2023 -> fc_dns_query_update_info: Software version from DNS: 0.103.11
> Sat Oct 28 10:15:22 2023 -> Current working dir is /var/lib/clamav/
> Sat Oct 28 10:15:22 2023 -> check_for_new_database_version: No local copy of "daily" database.
> Sat Oct 28 10:15:22 2023 -> query_remote_database_version: daily.cvd version from DNS: 27075
> Sat Oct 28 10:15:22 2023 -> daily database available for download (remote version: 27075)
> Sat Oct 28 10:15:22 2023 -> Retrieving https://database.clamav.net/daily.cvd
> Sat Oct 28 10:15:22 2023 -> downloadFile: Download source:      https://database.clamav.net/daily.cvd
> Sat Oct 28 10:15:22 2023 -> downloadFile: Download destination: /var/lib/clamav/tmp.d42c387a26/clamav-4284f543a7edbedf957130d2e000d883.tmp
> *   Trying 104.16.219.84:443...
> * Connected to database.clamav.net (104.16.219.84) port 443 (#0)
> * ALPN: offers h2,http/1.1
> *  CAfile: /etc/ssl/certs/ca-certificates.crt
> *  CApath: /etc/ssl/certs
> * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
> * ALPN: server accepted h2
> * Server certificate:
> *  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
> *  start date: May 15 00:00:00 2023 GMT
> *  expire date: May 14 23:59:59 2024 GMT
> *  subjectAltName: host "database.clamav.net" matched cert's "database.clamav.net"
> *  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
> *  SSL certificate verify ok.
> * using HTTP/2
> * h2h3 [:method: GET]
> * h2h3 [:path: /daily.cvd]
> * h2h3 [:scheme: https]
> * h2h3 [:authority: database.clamav.net]
> * h2h3 [user-agent: ClamAV/1.0.3 (OS: Linux, ARCH: x86_64, CPU: x86_64, UUID: 3eefda92-843c-4038-bc45-82b4d15c3a1e)]
> * h2h3 [accept: */*]
> * Using Stream ID: 1 (easy handle 0x55807156aa10)
> > GET /daily.cvd HTTP/2
> Host: database.clamav.net
> user-agent: ClamAV/1.0.3 (OS: Linux, ARCH: x86_64, CPU: x86_64, UUID: 3eefda92-843c-4038-bc45-82b4d15c3a1e)
> accept: */*
> connection: close
> 
> * old SSL session ID is stale, removing
> < HTTP/2 403
> < date: Sat, 28 Oct 2023 08:15:22 GMT
> < content-type: text/html; charset=UTF-8
> < x-frame-options: SAMEORIGIN
> < referrer-policy: same-origin
> < cache-control: max-age=15
> < expires: Sat, 28 Oct 2023 08:15:37 GMT
> < set-cookie: __cf_bm=GoInSh6ThKulzn.xWJ_6BassJffOFtmdRE4nBBvn9_s-1698480922-0-AfWe0qwScli5WjEIwVprZQhno2wVLd/bxWX7wDgjXo2zb2QPD8shrL3O4ZMuRlukdGTWkdd7BovWaGTTI6o9fsw=; path=/; expires=Sat, 28-Oct-23 08:45:22 GMT; domain=.clamav.net; HttpOnly; Secure; SameSite=None
> < strict-transport-security: max-age=15552000
> < x-content-type-options: nosniff
> < server: cloudflare
> < cf-ray: 81d1bb051ef9906a-FRA
> <
> * Connection #0 to host database.clamav.net left intact
> Sat Oct 28 10:15:22 2023 -> Saved freshclam.dat
> WARNING: Sat Oct 28 10:15:22 2023 -> Can't download daily.cvd from https://database.clamav.net/daily.cvd
> WARNING: Sat Oct 28 10:15:22 2023 -> FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN).
> Sat Oct 28 10:15:22 2023 -> This could mean several things:
> Sat Oct 28 10:15:22 2023 ->  1. You are running an out-of-date version of ClamAV / FreshClam.
> Sat Oct 28 10:15:22 2023 ->     Ensure you are the most updated version by visiting https://www.clamav.net/downloads
> Sat Oct 28 10:15:22 2023 ->  2. Your network is explicitly denied by the FreshClam CDN.
> Sat Oct 28 10:15:22 2023 ->     In order to rectify this please check that you are:
> Sat Oct 28 10:15:22 2023 ->    a. Running an up-to-date version of FreshClam
> Sat Oct 28 10:15:22 2023 ->    b. Running FreshClam no more than once an hour
> Sat Oct 28 10:15:22 2023 ->    c. If you have checked (a) and (b), please open a ticket at
> Sat Oct 28 10:15:22 2023 ->       https://github.com/Cisco-Talos/clamav/issues
> Sat Oct 28 10:15:22 2023 ->       and we will investigate why your network is blocked.
> WARNING: Sat Oct 28 10:15:22 2023 -> You are on cool-down until after: 2023-10-29 09:15:22
> ERROR: Sat Oct 28 10:15:22 2023 -> Database update process failed: Forbidden; Blocked by CDN
> ERROR: Sat Oct 28 10:15:22 2023 -> Update failed.

BR,
Manuel

**Comment by micahsnyder** [comment]
Hi @maglan2101,

We reached out with a ticket to Cloudflare because the `cf-ray` ID still didn't show any logs for us.  They investigated and found that your IP is being blocked based on geo IP rules for the Russia sanctions.  Presumably their geo-IP check is incorrect if your IP is in fact German and not Russian. 

But since it's not hitting our rules I'm not sure what we can do.  We also have to block Russian IP's with our own rules too, but we try to fix our rules when the there is a bad geo-IP result.

**Comment by maglan2101** [comment]
Hello,

yes, the IP is German and my server is located in Germany.
I hope Cloudfare can fix the geoIP check issue.

Thank you.

BR,
Manuel

**Comment by micahsnyder** [comment]
Hi @maglan2101 I think it may be fixed.  Please try again.

**Comment by maglan2101** [comment]
Hello,

now it works - great!
Thank you very much.

BR,
Manuel
