### ISSUE TITLE
Blocked Access to ClamAV Database Mirrors (403 Forbidden)

### ISSUE THREAD

**Issue by giga758** [Cisco-Talos/clamav#1431]
I am encountering a `403 Forbidden` error when attempting to update ClamAV virus databases using FreshClam or directly through wget. The issue appears to be related to restrictions from the ClamAV CDN. Below are the details:

- **ClamAV Version**: 1.4.1
- **FreshClam Version**: 1.4.1
- **OS**: Linux

**Error Message**:

ERROR: FreshClam received error code 403 from the ClamAV Content Delivery Network (CDN). 
ERROR: Database update process failed: Forbidden; Blocked by CDN.

**Steps Taken**:
1. Confirmed that ClamAV and FreshClam are up-to-date.
2. Attempted to download databases directly from the following URLs:
   - https://database.clamav.net/main.cvd
   - https://database.clamav.net/daily.cvd
   - https://database.clamav.net/bytecode.cvd
3. Tried using alternative mirrors:
   - https://db.us.clamav.net
   - https://db.eu.clamav.net
4. Verified that my configuration complies with ClamAV’s documentation and the FreshClam usage policy.

The issue persists across all attempts.

**Request**:
Please verify if there are any known restrictions or blocking rules affecting the ClamAV CDN. I would appreciate guidance on how to resolve this issue or if there are alternative mirrors available that can bypass the restrictions.

Describe the bug
----------------

Replace this text with a clear and concise description of the bug or feature request.

How to reproduce the problem
----------------------------

Replace this text with specific steps needed to reproduce the issue.

Replace this text with the output from the ClamAV command:
    clamconf -n

Attachments
-----------

If the issue is reproducible only when scanning a specific file, attach it to the ticket.

**Comment by Ashraf-wan** [comment]
I also got that problem. I cant run freshclam.exe. I am able to visit database.clamav.net and download the daily.cvd manually but running freshclam.exe will always error with connection fail.

**Comment by micahsnyder** [comment]
We restrict downloads to the Freshclam and CVDUpdate clients.  You should not be able to use a browser, curl, wget, etc to download the CVD files. The alternative mirrors (https://db.us.clamav.net/, etc) all point to the same cloudflare CDN now as database.clamav.net.

If you're getting a 403 forbidden message. It's possible we're blocking you based on location because of sanctions (sometimes that gets it wrong and we need to make adjustments), or you're being blocked by cloudflare (they do something similar). 

If you can grab the CF-RAY ID from the HTTP response message from Cloudflare when you run `freshclam --verbose`, we can look up that ID in the logs to see what's going wrong.  

Tip: If you've run freshclam already within the last 24 hours, it will back off to reduce network traffic and won't get that CF-RAY ID. You may need to delete the `freshclam.dat` file from the clamav database directory and try again. See also https://github.com/Cisco-Talos/clamav/issues/1287#issuecomment-2189183868

**Comment by MarkyMarkDE** [comment]
my options from freshclam.conf
```
DatabaseOwner clamav
DNSDatabaseInfo current.cvd.clamav.net
DatabaseMirror https://db.local.clamav.net
DatabaseMirror https://db.de.ipv6.clamav.net
DatabaseMirror https://db.dk.ipv6.clamav.net
DatabaseMirror https://db.pl.ipv6.clamav.net
DatabaseMirror https://db.cz.ipv6.clamav.net
DatabaseMirror https://db.at.ipv6.clamav.net
DatabaseMirror https://db.ch.ipv6.clamav.net
DatabaseMirror https://db.fr.ipv6.clamav.net
DatabaseMirror https://db.lu.ipv6.clamav.net
DatabaseMirror https://db.be.ipv6.clamav.net
DatabaseMirror https://db.nl.ipv6.clamav.net
DatabaseMirror https://db.us.ipv6.clamav.net
DatabaseMirror https://database.clamav.net
Bytecode yes
TestDatabases yes
CompressLocalDatabase no
DatabaseCustomURL file:///var/lib/clamav/whitelist.wdb
```
are working perfectly.
@micahsnyder my previous problems with .cld instead of .cvd are solved with that too (added explicitly https|http and ipv4|ipv6).

**Comment by micahsnyder** [comment]
@giga758  Are you still having issues with access?

**Comment by Rial-support** [comment]
I have the same problem. I am not in Russia and waiting more than 24 hours does not solve the problem. When I try to log into the site I get an error

![Image](https://github.com/user-attachments/assets/92875c3d-730f-495f-a554-366db39aef45)

**Comment by MarkyMarkDE** [comment]
> I have the same problem. I am not in Russia and waiting more than 24 hours does not solve the problem. When I try to log into the site I get an error
> 
> ![Image](https://github.com/user-attachments/assets/92875c3d-730f-495f-a554-366db39aef45)

your IP is from Ukraine, maybe that's the same as from Russia (blocked)
[82.207.97.10](https://www.infobyip.com/ip-82.207.97.10.html)

**Comment by Rial-support** [comment]
Ukraine is not Russia. This IP 194.242.96.186 is also from Ukraine, but it works from it

**Comment by Rial-support** [comment]
Who can I contact to remove my address from the blacklist or at least understand the reason for the blocking

**Comment by JTBrinkmann** [comment]
FYI I stumbled on this problem because I had a container image with an outdated clamav version (unlike OP). Updating clamav fixed the issue for me.
Cloudflare blocking browser access to the URL seems to be normal, I guess, as its restricted to (up to date) clamav user agents.

**Comment by val-ms** [comment]
@Rial-support 
> Who can I contact to remove my address from the blacklist or at least understand the reason for the blocking

I am sorry I didn't see your comment on this ticket back in March. IP address geo fencing is not always accurate especially as internet service providers are frequently shifting IP blocks.  IP addresses Ukraine, Germany, and some other countries occasionally get blocked as a result. We can usually fix it when this happens.  

If it happens to you again, or is still happening - please reach out and maybe even make a new ticket for your specific issue so it's less likely to slip through the cracks. 

I never heard a response from @giga758 though so I am going to close this ticket.
